Repository camelot-dev/camelot, pull requests merged in 2025-08, with the labels that each got.

#595 Fix release and metadata
  pyproject.toml
Labels: bug, build

#606 Release v1.0.7
  .github/workflows/release.yml
  pyproject.toml
Labels: ci, github_actions

#608 release v1.0.9
  .github/workflows/release.yml
  pyproject.toml
Labels: ci, github_actions

#609 Re-order actions in github release
  .github/workflows/release.yml
Labels: ci, github_actions

#566 docs: update branch name in docs
  README.md
  docs/conf.py
  docs/index.rst
  docs/user/advanced.rst
Labels: documentation

#558 [MRG] Minor update to install instructions and license statements
  README.md
Labels: documentation, dependencies

#568 Update pdfium_backend.py (close open documents)
  camelot/backends/pdfium_backend.py
Labels: bug

#611 Fix: Replace print with logger.warning for warnings
  camelot/parsers/base.py
Labels: bug
